### ISSUE TITLE
F-Droid again?

### ISSUE THREAD

**Issue by namazso** [Notsfsssf/Pix-EzViewer#68]
Have you considered getting the app packaged for F-Droid now that Play removed it?

According to [exodus](https://reports.exodus-privacy.eu.org/en/reports/com.perol.asdpl.play.pixivez/latest/) there are no trackers in the 1.3.12 version, not sure if there are any other non-free dependencies or trackers added since.

**Comment by Notsfsssf** [comment]
Hello, my app is blocked by Google because it references ‘bugly’ dependency, although you can see my code avoids ‘bugly’ being enabled on Google Store
I decided to use flutter to rewrite this application, which has been officially released. However, less than a week after the app was launched, Google still removed my app from Google Play on the grounds of “explicit porn”. I clearly stated in the rating report that my app contains some user-generated porn Content, but this does not work.
So you can choose to download the flutter [version](https://github.com/Notsfsssf/pixez-flutter) or the native version mentioned in the readme, which is taken over by another developer.
I  considered uploading [Pixez-Flutter](https://github.com/Notsfsssf/pixez-flutter) to F droid store, but I have encountered some technical problems.

**Comment by namazso** [comment]
Oh, didn't notice the native version's takeover.

You might want to consider adding an english warning, and maybe archiving the repository, as from what i understood this repo is discontinued now.

Thanks for help
